// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzqMQjyGpEq_VHHssxpI334zG47bEeL1w',
    appId: '1:426018642682:web:ed69b66ff4916b89b4c743',
    messagingSenderId: '426018642682',
    projectId: 'expense-tracker-5b2cc',
    authDomain: 'expense-tracker-5b2cc.firebaseapp.com',
    storageBucket: 'expense-tracker-5b2cc.appspot.com',
    measurementId: 'G-L9L7VKDV9L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlZULcPkEhmX9zW3Am3eUr5npo-Q8XB5k',
    appId: '1:426018642682:android:af1a32eb4684703eb4c743',
    messagingSenderId: '426018642682',
    projectId: 'expense-tracker-5b2cc',
    storageBucket: 'expense-tracker-5b2cc.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzqMQjyGpEq_VHHssxpI334zG47bEeL1w',
    appId: '1:426018642682:web:01dbc3b748e341d6b4c743',
    messagingSenderId: '426018642682',
    projectId: 'expense-tracker-5b2cc',
    authDomain: 'expense-tracker-5b2cc.firebaseapp.com',
    storageBucket: 'expense-tracker-5b2cc.appspot.com',
    measurementId: 'G-21G61B64BB',
  );
}
